# Титаник. Кто выживет?

https://www.kaggle.com/c/titanic/

In [1]:
import numpy as np
import pandas as pd

In [2]:
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

%config InlineBackend.figure_format = 'retina'
from pylab import rcParams
rcParams['figure.figsize'] = (9, 6)

### Данные

In [3]:
train = pd.read_csv('titanic/train.csv')
test = pd.read_csv('titanic/test.csv')

In [4]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB


### Фичи

чтобы одинаковым образом обработать train и test и не дублировать все операции 2 раза, соединим эти два набора данных в один, не забыв при этом:
1. выкинуть целевую переменную из train
2. проверить на соответствие набора признаков друг другу
3. добавить флаг того, является ли объект тестовым или нет

In [7]:
y_train = train.Survived
train.drop('Survived', axis=1, inplace=True)

In [8]:
train.columns == test.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [9]:
train['is_test'] = 0
test['is_test'] = 1

In [10]:
df = pd.concat([train, test])

супер, теперь полный набор данных можно обрабатывать вместе и в любой момент, уже обработанными, обратно разъединить на обучающую и тестовую выборки

Пол male/female закодируем в 1/0 и удалим переменные, с которыми мы не будем сейчас работать

In [11]:
df["isMale"] = df.Sex.replace({"male": 1, "female":0})
df.drop(["Sex", "Cabin", "Ticket", "Name", "PassengerId"], axis=1, inplace=True)

признаки, значения которых составляют небольшой перечислимый набор, закодируем в отдельные столбцы 

In [12]:
df_dummies = pd.get_dummies(df, columns=['Pclass', 'Embarked'])

In [13]:
df_dummies.head(10)

Age  SibSp  Parch     Fare  is_test  isMale  Pclass_1  Pclass_2  Pclass_3  \
0  22.0      1      0   7.2500        0       1         0         0         1   
1  38.0      1      0  71.2833        0       0         1         0         0   
2  26.0      0      0   7.9250        0       0         0         0         1   
3  35.0      1      0  53.1000        0       0         1         0         0   
4  35.0      0      0   8.0500        0       1         0         0         1   
5   NaN      0      0   8.4583        0       1         0         0         1   
6  54.0      0      0  51.8625        0       1         1         0         0   
7   2.0      3      1  21.0750        0       1         0         0         1   
8  27.0      0      2  11.1333        0       0         0         0         1   
9  14.0      1      0  30.0708        0       0         0         1         0   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1  
5           0           1           0  
6           0           0           1  
7           0           0           1  
8           0           0           1  
9           1           0           0

In [14]:
df_dummies.isnull().sum()

Age           263
SibSp           0
Parch           0
Fare            1
is_test         0
isMale          0
Pclass_1        0
Pclass_2        0
Pclass_3        0
Embarked_C      0
Embarked_Q      0
Embarked_S      0
dtype: int64

In [15]:
X_train = df_dummies[df_dummies.is_test==0].drop('is_test', axis=1)
X_test = df_dummies[df_dummies.is_test==1].drop('is_test', axis=1)

In [16]:
columns = X_train.columns

In [17]:
X_train.head(10)

Age  SibSp  Parch     Fare  isMale  Pclass_1  Pclass_2  Pclass_3  \
0  22.0      1      0   7.2500       1         0         0         1   
1  38.0      1      0  71.2833       0         1         0         0   
2  26.0      0      0   7.9250       0         0         0         1   
3  35.0      1      0  53.1000       0         1         0         0   
4  35.0      0      0   8.0500       1         0         0         1   
5   NaN      0      0   8.4583       1         0         0         1   
6  54.0      0      0  51.8625       1         1         0         0   
7   2.0      3      1  21.0750       1         0         0         1   
8  27.0      0      2  11.1333       0         0         0         1   
9  14.0      1      0  30.0708       0         0         1         0   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1  
5           0           1           0  
6           0           0           1  
7           0           0           1  
8           0           0           1  
9           1           0           0

### Заполнение пустых значений

заполним пустые значения средними по соответственным признакам

In [18]:
from sklearn.preprocessing import Imputer

In [19]:
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0, verbose=0, copy=True)

In [20]:
imputer.fit(X_train)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [45]:
imputer.fit(X_test)


Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [47]:
X_test_imputed = imputer.transform(X_test)
X_test_imputed = pd.DataFrame(X_test_imputed, columns=columns)

In [21]:
X_train_imputed = imputer.transform(X_train)
X_train_imputed = pd.DataFrame(X_train_imputed, columns=columns)

In [22]:
X_train_imputed.head(10)

Age  SibSp  Parch     Fare  isMale  Pclass_1  Pclass_2  Pclass_3  \
0  22.000000    1.0    0.0   7.2500     1.0       0.0       0.0       1.0   
1  38.000000    1.0    0.0  71.2833     0.0       1.0       0.0       0.0   
2  26.000000    0.0    0.0   7.9250     0.0       0.0       0.0       1.0   
3  35.000000    1.0    0.0  53.1000     0.0       1.0       0.0       0.0   
4  35.000000    0.0    0.0   8.0500     1.0       0.0       0.0       1.0   
5  29.699118    0.0    0.0   8.4583     1.0       0.0       0.0       1.0   
6  54.000000    0.0    0.0  51.8625     1.0       1.0       0.0       0.0   
7   2.000000    3.0    1.0  21.0750     1.0       0.0       0.0       1.0   
8  27.000000    0.0    2.0  11.1333     0.0       0.0       0.0       1.0   
9  14.000000    1.0    0.0  30.0708     0.0       0.0       1.0       0.0   

   Embarked_C  Embarked_Q  Embarked_S  
0         0.0         0.0         1.0  
1         1.0         0.0         0.0  
2         0.0         0.0         1.0  
3         0.0         0.0         1.0  
4         0.0         0.0         1.0  
5         0.0         1.0         0.0  
6         0.0         0.0         1.0  
7         0.0         0.0         1.0  
8         0.0         0.0         1.0  
9         1.0         0.0         0.0

### Разделение на обучающую и тестирующую выборки

In [23]:
from sklearn.model_selection import train_test_split

In [26]:
X_train_fin, X_val, y_train_fin, y_val = train_test_split(X_train_imputed, y_train, test_size=0.2)

In [27]:
X_train_fin.shape

(712, 11)

In [28]:
X_val.shape

(179, 11)

In [32]:
X_test_imputed = imputer.transform(X_test)

In [33]:
X_test_imputed.shape

(418, 11)

In [30]:
y_train_fin.shape

(712,)

In [31]:
y_val.shape

(179,)

Оценка точности

In [77]:
from sklearn.metrics import accuracy_score

In [82]:
clf = DecisionTreeClassifier(max_depth=3)

In [83]:
clf.fit(X_train_fin, y_train_fin)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [84]:
y_val_pred = clf.predict(X_val)

In [85]:
accuracy_score(y_val, y_val_pred)

0.7988826815642458

In [81]:
?DecisionTreeClassifier

In [52]:
from sklearn.model_selection import GridSearchCV

In [53]:
params = [ {'max_depth': list( range(1, 20) )} ]

In [54]:
gs = GridSearchCV( DecisionTreeClassifier(), param_grid = params, scoring = 'accuracy' )

In [55]:
gs.fit( X_train_fin, y_train_fin )

GridSearchCV(cv=None, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='accuracy', verbose=0)

In [56]:
gs.cv_results_

{'mean_fit_time': array([ 0.00133363,  0.00133348,  0.00166678,  0.00166678,  0.00133332,
         0.00233348,  0.00300026,  0.00200025,  0.00200025,  0.00200017,
         0.00200009,  0.00100025,  0.00233356,  0.00200033,  0.00133332,
         0.0016667 ,  0.00200009,  0.00100025,  0.00133355]),
 'mean_score_time': array([ 0.00100001,  0.00033339,  0.00066678,  0.00033331,  0.00066678,
         0.        ,  0.0006667 ,  0.00033339,  0.        ,  0.        ,
         0.00033339,  0.00099993,  0.00033347,  0.00033339,  0.00066686,
         0.00033339,  0.        ,  0.00100017,  0.00099993]),
 'mean_test_score': array([ 0.78932584,  0.7752809 ,  0.80617978,  0.80477528,  0.78651685,
         0.79634831,  0.79775281,  0.78651685,  0.78511236,  0.76966292,
         0.77106742,  0.7738764 ,  0.76825843,  0.76544944,  0.76966292,
         0.76123596,  0.77808989,  0.76825843,  0.76685393]),
 'mean_train_score': array([ 0.78933683,  0.79985285,  0.82865889,  0.83498505,  0.85674987,
         

In [57]:
gs.best_params_

{'max_depth': 3}

In [76]:
gg = gs.best_params_

dict_values([3])

### Обучение с кросс-валидацией

кросс-валидация поможет нам подобрать лучший параметр регуляризации

In [47]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

In [48]:
cs = 10**np.linspace(-3,1,5)
cs

array([  1.00000000e-03,   1.00000000e-02,   1.00000000e-01,
         1.00000000e+00,   1.00000000e+01])

In [49]:
grid = {'C': cs}#, 'max_features': features_num}
gridsearch = GridSearchCV(LogisticRegression(), grid, scoring='accuracy', cv=5)

In [50]:
%%time
gridsearch.fit(X_train_fin, y_train_fin)

CPU times: user 130 ms, sys: 3.18 ms, total: 133 ms
Wall time: 136 ms


GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': array([  1.00000e-03,   1.00000e-02,   1.00000e-01,   1.00000e+00,
         1.00000e+01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='accuracy', verbose=0)

In [51]:
sorted(gridsearch.grid_scores_, key = lambda x: -x.mean_validation_score)

/Applications/Utilities/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_search.py:667: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)


[mean: 0.79635, std: 0.03277, params: {'C': 0.10000000000000001},
 mean: 0.79354, std: 0.03196, params: {'C': 1.0},
 mean: 0.79354, std: 0.03196, params: {'C': 10.0},
 mean: 0.78652, std: 0.02524, params: {'C': 0.01},
 mean: 0.76545, std: 0.02022, params: {'C': 0.001}]

In [52]:
gridsearch.best_params_

{'C': 0.10000000000000001}

In [53]:
best_C = gridsearch.best_params_["C"]

# Оценка точности

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
clf = LogisticRegression(C=best_C)

In [56]:
clf.fit(X_train_fin, y_train_fin)

LogisticRegression(C=0.10000000000000001, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [57]:
y_val_pred = clf.predict(X_val)

In [58]:
accuracy_score(y_val, y_val_pred)

0.83240223463687146

# Финальное предсказание

In [59]:
clf.fit(X_train_imputed_scaled, y_train)

LogisticRegression(C=0.10000000000000001, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

предсказание вероятностей принадлежности классу 0 и 1:

In [60]:
clf.predict_proba(X_test_imputed_scaled)[:10]

array([[ 0.87122043,  0.12877957],
       [ 0.63004594,  0.36995406],
       [ 0.84442941,  0.15557059],
       [ 0.88731227,  0.11268773],
       [ 0.44402082,  0.55597918],
       [ 0.83691507,  0.16308493],
       [ 0.33409292,  0.66590708],
       [ 0.76813556,  0.23186444],
       [ 0.24424208,  0.75575792],
       [ 0.91289155,  0.08710845]])

предсказание номера класса:

In [61]:
predictions = clf.predict(X_test_imputed_scaled)
predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

In [62]:
submussion = 'PassengerId,Survived\n'
submussion += "\n".join(["{},{}".format(pid, prediction) for pid, prediction in zip(test.PassengerId, predictions)])

In [63]:
with open('submission.txt', 'w') as file:
    file.write(submussion)

In [73]:
for col, val in zip(X_train.columns, clf.coef_[0]):
    print("{:30} {:.2f}".format(col, val))

Age                            -0.43
SibSp                          -0.29
Parch                          -0.06
Fare                           0.13
isMale                         -1.17
Pclass_1                       0.43
Pclass_2                       0.09
Pclass_3                       -0.44
Embarked_C                     0.06
Embarked_Q                     0.03
Embarked_S                     -0.13


Регрессия позволяет посмотреть влияние различных факторов на принятое решение. Так, видно, что женский пол, маленький возраст и первый класс являлись сильными предпосылками к выживанию